<Incrementador>:
    orientation: 'vertical'
    ScrollView:
        BoxLayout:
            id: box 
            orientation: 'vertical'
            size_hint_y:None
            height: self.minimum_height
    BoxLayout:
        size_hint_y:None
        height:60
        TextInput:
            id: texto
        Button:
            text: '+'
            size_hint_x:None
            width:60
            on_release:root.addwidget()


<Incrementado>:
    height:200
    size_hint_y:None
    Label:
        id: label
        font_size: 30
    Button:
        text: 'x'
        size_hint_x: None
        width: 60
        on_release: app.root.ids.box.remove_widget(root)